# Generates assets/tiles/ocean.png (128x64, seamless both axes) from an ASCII
# pixel grid. Classic flat arcade water in the Xevious/1942 tradition: solid
# navy that reads as flat color at a glance, a whisper-subtle darker mottle
# (barely one value step down — texture at this contrast reads as water
# grain, not pattern), and a few sparse white flecks. Earlier texture-heavy
# attempts (dithered chevrons, swell bands, dappled patches) each read as
# pattern/fabric rather than water; the lesson was contrast, so this tile
# keeps everything within a whisper of the base tone except the rare flecks.
#
# The grid was authored offline (periodic value noise for the mottle,
# hand-placed flecks); this script holds the baked result so the asset is
# exactly reproducible, same convention as the sprite generators.
#
# Run from anywhere:  powershell -File tools/gen-ocean-tile.ps1

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$palette = @{
    'B' = [System.Drawing.Color]::FromArgb(255, 20, 72, 116)    # navy base    #144874
    'M' = [System.Drawing.Color]::FromArgb(255, 17, 62, 102)    # faint mottle #113e66
    'F' = [System.Drawing.Color]::FromArgb(255, 207, 239, 240)  # white fleck  #cfeff0
}

$grid = @(
    "BBBBBBBBBBBBBBBBBBBBBBBBBMMMMMBBBBBMMMMMMMBBBBBBBBBBBBBBBBMMMMMBBBBBBBBMMMMMMMMBBBMMMMMMMMMMMMMBBBBBBBBBBBBBBMMMMMMMMMBBBBBBBBBB",
    "BBBBBBBBBBBBMBBBBBBBBBBBBMMMMMMBBBBMMMMMMMBBBBBBBBBBBBBBBBMMMMMBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBMMMMMMMMMBBBBBBBBBB",
    "BBBBBBBBBBBBMMBBBBBBBBBBBMMMMMMMBBBBMMMMMMBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBMMMBBBBBBBBBBBBBBBBBBMMMMMMMBBBBBBBBBB",
    "BBBMMMBBBBBMMMMMMMMMMMMBBMMMMMMMMMMBBBBMMMBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMBBBBBBBBB",
    "BMMMMMBBBBBMMMMMMMMMMMMBBMMMMMMMMMMBBBBMMMBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMBBBBBBBBB",
    "BBMMMMBBBBBMMMMMMMMMMMMMBMMMMMMMMMMBBBBBMBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMBBBBBBBBB",
    "BBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMBBBBMMBBB",
    "BBBBBBMMMMMMFMMMMMMMBBMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBMBBBBBBBBBBMMMMMMMMMMMBBBBBBBBBBMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMBBBBMMMBBB",
    "BBBBBBMMMMMMMMMMMMMMBBMMMMMMMMMMMMMMMMMBBBBBBBBBBBBMMMBBBBBBBBBMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMBBBBMMMMBB",
    "BBBBBBMMMMMMMMMMMMMBBBBMMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMBBBBBBBBBMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBFBBBBBBBBBBBBBBBBBBBBBBBBMMMBB",
    "BBBBBBMMMMMMMMMMMMMBBBBMMMMMMMMMMMMMBBBBBBBBBBBBBBBBMBBBBBBBBBMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMBBB",
    "BBBBBBMMMMMMMMMMMBBBBBBMMMMMMMMBBBBBBBBBBBBBMBBBBBBBBBBBBBBBBBMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMBBBBBBBBBBBBBBBBBBBBBBBMBBB",
    "MBBBBBMMMMMMMMMBBBBBBBBBMMMBBBBBBBBBBBBBBBBMMMBBBBBBMBBBBBBBBBMMMMMBBBBBBBBBBBBBBBBBBBBMMMBBBBBBBBBMMMMBBBMMMMBBBBBBBBBBBBBBMMMM",
    "MBBBBBMMMMMMMMMBBBBBBBBBMMBBBBBBBBBBBBBBBBBMMMBBBBBBMMBBBBBBBBMMMMMBBBBBBBBBBBBMMMBBBBBBMBBBBBBBBBBMMMMMMMMMMMBBBBBBBBBBBBBBMMMM",
    "MMMMMMMMMMMMMMBBBBBBBBBBBBBMMBBBBBBBBBBBBBBMMMBBBBBMMMBBBFFMMMMMMMMMBBBBBBBBBBBMMMBBBBBBBBBBBBBBBBBMMMMMMMMMMMBBBBBBBBBBBBBBBMMM",
    "MMMMMMMMMMMMMBBBBBBMMMMBBBBMMMBBBBBBBBBBBBBBBMMMMMMMMMMBBBMMMMMMMMMMMMBBBBBBBBMMMMBBBBBBBBBMMMBBBBBBMMMMMMMMMBBBBBBBBBBBBBBBBMMM",
    "MMMMMMMMMMMMMBBBBBBMMMMBBBBMMMBBBBBBBBBBBBBBBBMMMMMMMMMBBBMMMMMMMMMMMMBBBBBBBBMMMMBBBBBBBBBMMMBBBBBBBMMMMMMMBBBBBBBBBBBBBBBBBBMM",
    "MMMMMMMMMMMMMBBBBBBMMMMBBBMMMMBBBBBBBBBBBBBBBBMMMMMMMMBBBBMMMMMMMMMMMMBBBBBBBMMMMMBBBBBBBBBBMMBBBBBBMMMMMMMMBBBBBBBBBBBBBBBBBBBM",
    "BBMMMMMMMMMMBBBBBBBMMMMMBMMMMMMBBBBBBBBBBBBBBBBMMMMMMMBBBBBBBBBMMMMMMMBBBBBBMMMMMMBBBBBBBBBBBBBBBBBMMMMMMMMMBBBBBBBBBBBBBBBBBBBB",
    "BBMMMMMBBBBBBBBBBBBBMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMBBBBBMMMMBBBBBBBBBBBBBBBBBBBMMMMMMMMMMBBBBBBBBBBBBBBBBBBBB",
    "BBMMMMMBBBBBBBBBBBBBBMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMBBBBBMMMMBBBBBBBBBMBBBBBBBBBMMMMMMMMMMBBBBBBBBMBBBBBBBBBBB",
    "BBMMMMMBBBBBBBBBMMBBBMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMBBBBBMMMBBBBBBBBBBBBBBBBBBBBBMMMMMMMMMBBBBBBBMMMBBBBBBBBBB",
    "BBMMMMMMMMMBBBMMMMMBBBBMMMMMMMBBBBBBBBBBBBBBMMBBBBBMBBBBBBBBBBBBBBBBBBBBMMMMMMBBBBBBBBBBBBBBBBBBBBBBBMMMMMMBBBBBBBBMMMMMBBBBBBBB",
    "BMMMMMMMMMMMMMMMMMMBBBBBMMMMMMBBBBBBBBBBBBBMMMMBBBBMMBBBBBBBMMMBBBBBBBMMMMMMMMBBBBBBBBBBBBBBMBBBBBBBBBBMMMBBBBBBBBMMMMMMMMBBBBBB",
    "BMMMMMMMMMMMMMMMMMMBBBBBBMMMMBBBBBBBBBBBBBBMMMMBBBBMMBBBBBBMMMMMMBBBBBMMMMMMMBBBBBBBBBBBBBBMMMBBBBBBBBBMMMBBBBBBMMMMMMMMMMMBBBBB",
    "BBMMMMMMMMMMMMMMMMMBBBBMMMMMMMBBBBBBBBBBBBBBMMMBBBBMBBBBBBBMMMMMBBBBBBBMMMMMMMBBBBBBBBBBBBBMMBBBBBBBBBBMMMMBBBBMMMMMMMMMMMMBBBBB",
    "BBMMMMMMMMMMMMMMMMMMMMMMMMMMMMFBBBBBBBBBBBBBBBBMMMBBBBBBBBBMMMMBBBBBBBBMMMMMMMBBBBBBBBBBBBBBMBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMBBBBB",
    "BBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBMMMBBBBBBBBBMMMMBBBBBBBBBBBMMMMMMBMMMMBBBBBBBMBBBBBBBBBMMMMMMMMMMMMMMMFMMMMMMBBBB",
    "BBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMBBBBBBBBMMMMMBBBBBBBBBBBMMMMMMMMMMMMBBBBBBMMBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBB",
    "BBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMBBBBBBBBMMMMMBBBBBBBBBBBBMMMMMMMMMMMBBBBBMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMMBBBBB",
    "BBMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMMBBBBBBBBBBMMMMMMMMMMBBBBBMMMBBBBBMMMMMMMMMMMMMMMMBBBBBBBBBBBBB",
    "BBMMMMMMMMMBBBMMMMMMMMMMMMMBBBBBBBBBBBBBBBMMMMBBBBBBBBBBBBBBMMMMMMMBBBBBBBBBBBBBMMMMMMMBBBBMMMBBBBBMMMMMMMMMMMMMMMBBBBBBBBBBMMMB",
    "MMMMMMMMMMMBBBMMMMMMMMMMMMMBBBBBBBBBBBBBBBMMMMMBBBBBBBBBBBBBBMMMMMMBBBBBBBBBBBBBBMMMMMMBBBBMMMBBBBMMMMMMBMMMMMMMBBBBBBBBBBBBMMMM",
    "MMMMMMMMMMMBBBMMMMMMMMMMMMMBBBBBBBBBBBBBBBMMMMBBBBBBBBBBBBBBMMMMMMMBBBBBBBBBBBBBBFFMMMMBBBBMMMBBBBMMMMMMBBMMMMMMMBBBBBBBBBBBMMMM",
    "BMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBMMMBBBBBMMMMMBBBBBBBBBBBBBBMMMMMMMMMMBBBBBBBBBBBMMMMMMMMBBBBMMMMMBMMMMMMBBBBBMMMMMBBBBBBBBBBBBBBB",
    "BBBBMMBBBBMMMMMMMBBBBBMMMMMBBBMMMMMMMMMMMMMBBBBMMMMBBBMMMMMMMMMMMMMMMMMMMMBBBBBMMMMMMMMBBBBBMMMMMMMMMMMBBBBBBBBMMMBBBBBBMMBBBBBB",
    "BBBBBBBBBBBMMMMBBBBBBBBMMMMBBBMMMMMMMMMMMMMBBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBMMMMMMMMBBBBBBBMMMMMMMMMBBBBBBBBBMMBBBBBMMMBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBMMMMBBBMMMMMMMMMMMMMBBBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBBBBMMMMMMMMBBBBBBBMMMMMMMMBBBBBBBBBBMBBBBBBBMBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBMMMMBBBMMMMMMMMMMMMMMMMMMMMMMBBBMMMMMMMMMMMMMMMMMMMMBBBBMMMMMMMBBBBBBBBMMMMMMMMBBBBBBBBBMMBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBMMMMBBBMMMMMMMMMMMMMMMMMMMMMBBBBBBBMMMMMMMMBBBMMMMMMBBBBMMMMMMMBBBBBBBBBMMMMMMBBBBBBBMMMMMBBBBBBBBBBBBBBB",
    "BBBMMMMMMBBBBBBBBBBBBBBMMMMBBBMMMMMMMMMMMMMMMMMMMMMBBBBBBBBMMMMMBBBBBMMMMMMBBBBMMMMMMBBBBBBBBBBMMMMMMBBBBBBMMMMMMBBBBBBBBBBBBBBB",
    "BBBMMMBBBBBBBBBBBBBBBBBMMMMBBBMMMMMMMMMMMMMMMMMMMMMBBBBBBBBMMMMBBBBMMMMMMMMBBBBMMMMMBBBBBBBBBBBMMMMMMBBBBBBMMMMMMBBBBBBBBBBBBBBB",
    "MMMMMMBBBBBBBBBBBBBBBBBMMMBBBBBMMMMMMMMMBMMMMMMMMMMBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMBBBBBBBBBBBBMMMMMMMBBBBBBMMMMMMMBBBBBBBBBBBBB",
    "MMMMMMBBBBBBBBBBBBBBBBBMMMBBBBBBBBMMMMMBBBBMMMMMMMMBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMBBBBBBBBBMMBBBBMMMMBBBBBBBBMMMMMMMMBBBBBBBBBM",
    "MMMMMMMBBBBBBBBBBBBBBBBMMBBBBBBBBBMMMMMBBBBBMMMMMMBBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMBBBBBBBBMMMBBBBMMMMMBBBBBBBMMMMMMMMBBBBBBBBBM",
    "MMMMMMMMFFBBBBBBBBBBBBMMMBBBBBBBBBMMMMMBBBBBMMMMMMBBBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMBBBBBBBBBMBBBBBMMMMMBBBBBBMMMMMMMMMMBBBBBBBBM",
    "BMMMMMMMMMMBBBBBBBBBMMMMMMBBBBBMMMMMMMMBBBBBBMMMMMBBBBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMMMBBBBMMMMMMMMMMMMMMMBBBBBB",
    "BBBMMMMMMMMMMBBBBBBBMMMMMMBBBBMMMMMMMMMBBBBBBBBBBBBMBBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBMMMMMBBBBMMMMMMMMMMMMMMMMMMBBB",
    "BBBMMMMMMMMMMBBBBBBMMMMMMMMBBBMMMMMMMMMBBBBBBBBBBBBMMBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBMMMMMBBBBMMMMBBMMMMMMMMMMMMMBB",
    "BBBMMMMMMMMMMBBBBBBBMMMMMMMBBBMMMMMMMMMMBBBMMMMMMMMMBBBBBBBBBBMMMMMMMBBMMMMMMMMMMMMMMMBBBBBBBBBBBBBMMMMBBBBMMMMMBMMMMMMMMMMMMMBB",
    "BBBMMMMMMMMMMMBBBBBBMMMMMMMMMMMMMMMBBBMMMMMMMMMMMMMBBBBMMMBBBBMMMMMBBBBBMMMMMMMMMMMMMMBBBBBBBBBBBBBBMMBBBBMMMMMMMMMMMMMMMMMMMMBB",
    "BBBMMMMMMMMMMMBBBBBBBBMMMMMMMMMBBBBBBBMMMMMMMMMMMMMBBBMMMMMBBBBMMMBBBBBBBBBBBMMMMMMMMMBBBBBBBBBBBBBBBBBBBBMMMMMMMMMMMMBBBBMMMMMB",
    "BBBMMMMMMMMMMMMMMBBBBBBMMMMMMMMBBBBBBBMMMMMMMMMMFMMBBBMMMMMBBBBBMBBBBBBBMMBBBBBMMMMMMMMBBBBBMBBBBBBBBBBBBBMMMMMMMMMMMBBBBBBMMMMB",
    "BBBMMMMMMMMMMBBMMBBBBBBBMMMMMMMBBBBBBBMMMMMMMMMMMMMBBBMMMMMBBBBBBBBBBBBMMMMBBBBBBMMMMMMBBBBMMMBBBBBBBBBBBBMMMMMMMBBBBBBBBBBMMMMB",
    "BBBMMMMMMMBBBBBMMMBBBBBBMMMMMMMMMMMBBBMMMMMMMMMMMMBBBBMMMMBBBBBBBBBBBBBMMMMBBBBBBBBMMMMBBBMMMMMBBBBBBBBBBBBBBBBBBBBBBBBBBBBMMMMB",
    "BMMMMBBBBBBBBBBMMMBBBBBBMMMMMMMMMMMMBBMMMMMMMMMMBBBBBBMMMMBBBBBBBBBBBBMMMMMMBBBBBBBBBBBBBBMMMMMMMBBBBBMMFMBBBBBBBBBBBBBBBBBBMMMM",
    "MMMMBBBBBBBBBBBMMMBBBBBBMMMMMMMMMMMMBBMMMMMMMMMBBBBBBBMMMMBBBBBBBBBBBBMMMMMMBBBBBBBBBBBBBBMMMMMMMMBBBBMMMMBBBBBBBBBBBBBBBBBBBMMM",
    "BBBBBBBBBBBBBBBMMMBBBBBBBBMMMMMMMMMMMMMMMMMMMMMBBBBBBBMMMMBBBBBBBBBBBBMMMMMMBBBBBBBBBBMMMMMMMMMMMMBBBBMMMMBBBBBBBBBBBBBBBBBBBMMB",
    "BBBBBBBBBBBBBBBMMMBBBBBBBBMMMMMMMMMMMMMMBBMMMBBBBBBBMMMMMMMBBBBBBBBBBBMMMMMBBBBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBMMMBBBBBBBBBMMMMMMMMMMMMBBBBBBBBBBBBMMMMMMMMMMMMBBBBBBMMMMMMBBBBBBBMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBMMMBBBBBBBBBMMMMMMMMMMMMBBBBBBBBBBBBMMMMMBMMMMMMBBBBMMMMMMMMBBBBBBMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBMMBBBBBB",
    "BBBBBBBBBBBBBBBBMBBBBBBBBBMMMMMMMMMMMMMBBBBBBBBBBBBMMMMMBMMMMMMBBBBBBMMMMMMBBBBMMMMMMMMMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBBBMBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMBMMMMMMMBBBBBBBBBBBBMMMBBMMMMMMBBBBBBBMMMMMBBBBMMMMMMMMMMMMMMMMBBBBBBBBBBBBBBBMMMMMBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBMMMMMMBBBMMMMMMMMBBBBBBBBBBBBBBBBMMMMMBBBBBBBMMMMMMBMMBBMMMMMMMMMMMMMMBBBBBBBBBBBBBBMMMMMMMMMBBBBBBBBBB"
)

$width = 128
$height = 64
$bmp = New-Object System.Drawing.Bitmap $width, $height
for ($y = 0; $y -lt $height; $y++) {
    if ($grid[$y].Length -ne $width) { throw "row $y is $($grid[$y].Length) chars, expected $width" }
    for ($x = 0; $x -lt $width; $x++) {
        $bmp.SetPixel($x, $y, $palette[$grid[$y][$x].ToString()])
    }
}

$out = Join-Path $PSScriptRoot "..\assets\tiles\ocean.png"
$out = [System.IO.Path]::GetFullPath($out)
$bmp.Save($out, [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
Write-Host "written: $out"
