# Generates assets/tiles/ocean.png (64x64, seamless both axes) from an ASCII
# pixel grid. Dappled ocean per README design: organic blobby patches of
# lighter water over a darker base — reads as light playing on a gently
# moving surface rather than directional waves. No pixel-level dithering and
# only sparse foam flecks; dense high-frequency texture reads as fabric, not
# water (the failure mode of the original 32x32 dithered-chevron tile).
#
# The grid was authored offline with periodic value noise (fBm thresholded
# into three tones, foam gated by a second noise); this script holds the
# baked result so the asset is exactly reproducible, same convention as the
# sprite generators.
#
# Run from anywhere:  powershell -File tools/gen-ocean-tile.ps1

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$palette = @{
    'D' = [System.Drawing.Color]::FromArgb(255, 19, 62, 77)     # deep water  #133e4d
    'B' = [System.Drawing.Color]::FromArgb(255, 30, 96, 118)    # base water  #1e6076
    'L' = [System.Drawing.Color]::FromArgb(255, 42, 122, 143)   # light patch #2a7a8f
    'F' = [System.Drawing.Color]::FromArgb(255, 207, 239, 240)  # foam fleck  #cfeff0
}

$grid = @(
    "BBBBBBBBBBDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBLLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBBBBBDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBLLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBBBBDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBBBDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBLLLLLLBBBBBBBBBBBBBB",
    "DDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBLLLLBBBBBBBBBBDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBLLLBBBBBBBBBDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDBBBBBBBLLLLLLBBBBBBBBBBBBBBBBBBDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDBBBBBBBLLLLLLLBBBBBBBBBBBBBBBBBDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDBBBBBBLLLLLLLLBBBBBBBBBBBBBBBBBBDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDBBBBBBLLLLLLLLBBBBBBBBBBBBBBBBBBDDDDDDDD",
    "BBBBBBDDDDDDDDDDDDDDDDDBBBBBBBLLLLLLLBBBBBBBBBBBBBBBBBBBBDDDBBBB",
    "BBBBBBBBDDDDDDDDDDDDDBBBBBBBBBLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "LLLBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBLL",
    "LLLLBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBLLL",
    "LLLLLBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBLLLL",
    "LLLLLLBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBLLLL",
    "LLLLLLLBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBLLLLL",
    "LLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBLLLLLL",
    "LLLLLLLLLBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBBLLLLLL",
    "FFLLLLLLLLBBBBBBBBBBBBBBBBBLLLLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLFFF",
    "FFLLLLLLLLBBBBBBBBBBBBBBBBBLLLLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLFFF",
    "FFLLLLLLLLBBBBBBBBBBBBBBBBBLLLLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLFFF",
    "FLLLLLLLLBBBBBBBBBBBBBBBBBBBLLLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLFFF",
    "LLLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLLLLBBBBBBBBBBBBBBBBBBBBLLLLLLLL",
    "LLLLLLLLBBBBBBBBBBBBBBBBBBBBBBLLLLLBBBBBBBBBBBBBBBBBBBBLLLLLLLLL",
    "LLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLL",
    "LLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLL",
    "LLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLL",
    "LLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLL",
    "LLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLL",
    "LLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLL",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBLLLLLLLLLLBLLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBLLLLLLLLBBLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBLLLLLBBBBBBLLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBLLBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLLLLBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLLBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLLLLBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLLLBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLLLLLLLBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBDDDBBBBBBBBBBBBBBLLLLLLLLLLLLBBBBBBBBBBBBB",
    "BBBBBBBBBBBDDDDBBBBBBDDDDDDBBBBBBBBBBBBBLLLLLLLLLLLBBBBBBBBBBBBB",
    "BBBBBBBBBBBDDDDDBBBDDDDDDDDBBBBBBBBBBBBBBLLLLLLLLLLBBBBBBBBBBBBB",
    "BBBBBBBBBBDDDDDDDBBDDDDDDDDDBBBBBBBBBBBBBBLLLLLLLLBBBBBBBBBBBBBB"
)

$size = 64
$bmp = New-Object System.Drawing.Bitmap $size, $size
for ($y = 0; $y -lt $size; $y++) {
    if ($grid[$y].Length -ne $size) { throw "row $y is $($grid[$y].Length) chars, expected $size" }
    for ($x = 0; $x -lt $size; $x++) {
        $bmp.SetPixel($x, $y, $palette[$grid[$y][$x].ToString()])
    }
}

$out = Join-Path $PSScriptRoot "..\assets\tiles\ocean.png"
$out = [System.IO.Path]::GetFullPath($out)
$bmp.Save($out, [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
Write-Host "written: $out"
