# Generates assets/tiles/ocean.png (64x64, seamless both axes) from an ASCII
# pixel grid. Calm dark ocean per README design: mostly-flat deep navy with
# broad organic swell bands running horizontally (noise-warped so no two
# crests match), a lighter crest top, and rare 1px foam dashes on crest
# edges. Deliberately low-contrast and sparse — the glow-heavy sprites are
# meant to own the scene, and dense high-frequency texture reads as fabric,
# not water (the failure mode of the first-pass 32x32 dithered-chevron tile).
#
# The grid was authored offline with periodic value noise (fBm-warped sine
# bands); this script holds the baked result so the asset is exactly
# reproducible, same convention as the sprite generators.
#
# Run from anywhere:  powershell -File tools/gen-ocean-tile.ps1

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$palette = @{
    'D' = [System.Drawing.Color]::FromArgb(255, 10, 37, 48)     # deep water #0a2530
    'B' = [System.Drawing.Color]::FromArgb(255, 14, 49, 64)     # swell back #0e3140
    'S' = [System.Drawing.Color]::FromArgb(255, 25, 78, 96)     # crest top  #194e60
    'F' = [System.Drawing.Color]::FromArgb(255, 207, 239, 240)  # foam       #cfeff0
}

$grid = @(
    "BBBBSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBBBBBBBSSSSSSSBBBBBBBBBBBB",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFFSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSFFSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSSSSSBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSSSBBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "BBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "BBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBB",
    "BBBBBSSSSSBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBB",
    "SSSSFFFFFFFFSSBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDBBBBBBBBBBBBBBBSS",
    "SSSSSSSSSSSSFFFSSSSSSSSBBBBBBBBBBBBBBBBDDDBBBBBBBBBBBBBBBSSSSSSS",
    "SSSSSSSSSSSSSSSSSFFFFFFFFSSSBBBBBBBBBBBBBBBBBBBBBBBBBSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSFFFFSSSSBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBSSSFFFSSSSSSSSSSSSS",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "SSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "BBBBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSB",
    "BBBBBBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBB",
    "BBBBBBBBBBBBBBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBB",
    "BBBBBBDDDDDDDDDDDDDBBBBBBBBBSSSSSSSSSSSSSSSSSSSSSBBBBBBBBBBBBBBB",
    "BBBDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBSSSSSSSSSSSBBBBBBBBBBBBBBBBBBB",
    "DDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBSSSBBBBBBBBBBBBBBBDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDDDDBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DDDDDBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "BBBBBBBBBBBBSSSSSSSSBBBBBBBBBDDDDDDDDDDDDDDBBBBBBBBBBBBBDDBBBBBB",
    "BBBBBBBBSSSSSSSSSSSSSSSSSBBBBBBDDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBB"
)

$size = 64
$bmp = New-Object System.Drawing.Bitmap $size, $size
for ($y = 0; $y -lt $size; $y++) {
    if ($grid[$y].Length -ne $size) { throw "row $y is $($grid[$y].Length) chars, expected $size" }
    for ($x = 0; $x -lt $size; $x++) {
        $bmp.SetPixel($x, $y, $palette[$grid[$y][$x].ToString()])
    }
}

$out = Join-Path $PSScriptRoot "..\assets\tiles\ocean.png"
$out = [System.IO.Path]::GetFullPath($out)
$bmp.Save($out, [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
Write-Host "written: $out"
