#ifndef SEAVIOUS_STAGE_DATA_H
#define SEAVIOUS_STAGE_DATA_H

// Types for the compiled stage tables (src/stage1_data.c, generated by
// tools/gen-stage-table.py from the ASCII map — see README "Stage
// authoring format"). Events are sorted by px so the engine walks them
// with a cursor.

typedef enum {
    STAGE_SPAWN_DRONE,
    STAGE_SPAWN_DRONE_LINE3,
    STAGE_SPAWN_DRONE_V5,
    STAGE_SPAWN_INTERCEPTOR,
    STAGE_SPAWN_GUNSHIP,
    STAGE_SPAWN_CASEMATE,
    STAGE_SPAWN_TRACKING_TURRET,
    STAGE_SPAWN_RELAY_NODE,
    STAGE_SPAWN_MINE,
    STAGE_SPAWN_MOBILE_PLATFORM
} StageSpawnKind;

typedef struct {
    int px;        // scroll distance at which this event fires
    float laneY;   // lane center in play-area coordinates
    StageSpawnKind kind;
} StageSpawnEvent;

typedef struct {
    int px;        // left edge, map scroll-distance coordinates
    int y;         // top edge in play-area coordinates
    int widthPx;
    int heightPx;
} StageTerrainFootprint;

extern const StageSpawnEvent STAGE1_EVENTS[];
extern const int STAGE1_EVENT_COUNT;
extern const StageTerrainFootprint STAGE1_TERRAIN[];
extern const int STAGE1_TERRAIN_COUNT;
extern const int STAGE1_LENGTH_PX;

#endif
