// Generated by tools/gen-stage-table.py from assets/stages/stage3.txt
// - do not edit by hand; regenerate and commit instead. A drift
// test (tests/test_stage_table.py) keeps this in sync with the map.
#include "stage_data.h"

const StageSpawnEvent STAGE3_EVENTS[] = {
    { 64, 48.0f, STAGE_SPAWN_DRONE },
    { 320, 176.0f, STAGE_SPAWN_DRONE },
    { 448, 112.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 736, 272.0f, STAGE_SPAWN_DRONE },
    { 832, 80.0f, STAGE_SPAWN_CASEMATE },
    { 960, 240.0f, STAGE_SPAWN_DRONE },
    { 1120, 144.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 1408, 80.0f, STAGE_SPAWN_INTERCEPTOR },
    { 1472, 304.0f, STAGE_SPAWN_DRONE },
    { 1600, 176.0f, STAGE_SPAWN_TRACKING_TURRET },
    { 1728, 240.0f, STAGE_SPAWN_INTERCEPTOR },
    { 1856, 144.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 2144, 48.0f, STAGE_SPAWN_DRONE_LINE3 },
    { 2176, 208.0f, STAGE_SPAWN_MINE },
    { 2368, 176.0f, STAGE_SPAWN_MINE },
    { 2432, 272.0f, STAGE_SPAWN_DRONE_V5 },
    { 2560, 112.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 2848, 80.0f, STAGE_SPAWN_GUNSHIP },
    { 2912, 304.0f, STAGE_SPAWN_DRONE },
    { 3040, 176.0f, STAGE_SPAWN_MOBILE_PLATFORM },
    { 3168, 240.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 3296, 144.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 3584, 272.0f, STAGE_SPAWN_DRONE_LINE3 },
    { 3648, 48.0f, STAGE_SPAWN_RELAY_NODE },
    { 3744, 304.0f, STAGE_SPAWN_TRACKING_TURRET },
    { 3840, 176.0f, STAGE_SPAWN_DRONE },
    { 4000, 240.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 4096, 112.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 4320, 304.0f, STAGE_SPAWN_MINE },
    { 4352, 48.0f, STAGE_SPAWN_CASEMATE },
    { 4448, 208.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 4544, 112.0f, STAGE_SPAWN_INTERCEPTOR },
    { 4672, 176.0f, STAGE_SPAWN_TRACKING_TURRET },
    { 4800, 240.0f, STAGE_SPAWN_DRONE },
    { 4864, 80.0f, STAGE_SPAWN_ROGUE_WAVE },
    { 4928, 272.0f, STAGE_SPAWN_GUNSHIP },
    { 4992, 144.0f, STAGE_SPAWN_MINE },
    { 5280, 48.0f, STAGE_SPAWN_DRONE },
    { 5376, 240.0f, STAGE_SPAWN_DRONE },
    { 5504, 144.0f, STAGE_SPAWN_ROGUE_WAVE },
};

const int STAGE3_EVENT_COUNT = sizeof(STAGE3_EVENTS) / sizeof(STAGE3_EVENTS[0]);

const StageTerrainFootprint STAGE3_TERRAIN[] = {
    { 0, 0, 0, 0 }, // placeholder: no terrain authored
};

const int STAGE3_TERRAIN_COUNT = 0;

const StageTerrainHardpoint STAGE3_TERRAIN_HARDPOINTS[] = {
    { 0, 0 }, // placeholder: no hardpoints authored
};

const int STAGE3_TERRAIN_HARDPOINT_COUNT = 0;

const int STAGE3_LENGTH_PX = 5760;
