#ifndef SEAVIOUS_STAGE_DATA_H
#define SEAVIOUS_STAGE_DATA_H

// Types for the compiled stage tables (src/stage1_data.c, generated by
// tools/gen-stage-table.py from the ASCII map — see README "Stage
// authoring format"). Events are sorted by px so the engine walks them
// with a cursor.

typedef enum {
    STAGE_SPAWN_DRONE,
    STAGE_SPAWN_DRONE_LINE3,
    STAGE_SPAWN_DRONE_V5,
    STAGE_SPAWN_INTERCEPTOR,
    STAGE_SPAWN_GUNSHIP,
    STAGE_SPAWN_CASEMATE,
    STAGE_SPAWN_TRACKING_TURRET,
    STAGE_SPAWN_RELAY_NODE,
    STAGE_SPAWN_MINE,
    STAGE_SPAWN_MOBILE_PLATFORM,
    // Land glyphs also compile their cell as terrain + hardpoint pad
    // (the installation brings its mounting pad with it).
    STAGE_SPAWN_MORTAR_BATTERY,
    STAGE_SPAWN_DRONE_BUNKER
} StageSpawnKind;

typedef struct {
    int px;        // scroll distance at which this event fires
    float laneY;   // lane center in play-area coordinates
    StageSpawnKind kind;
} StageSpawnEvent;

typedef struct {
    int px;        // left edge, map scroll-distance coordinates
    int y;         // top edge in play-area coordinates
    int widthPx;
    int heightPx;
} StageTerrainFootprint;

// Ceiling on compiled terrain rects per stage: the island renderer's
// grouping pass walks fixed-size scratch arrays sized to this, and
// stage_tests assert every stage's table fits. The contract exists
// because Stage 2 once shipped 43 rects past a silent 32-rect render
// cap: every island went invisible while collision still used them,
// and torpedoes died against open-looking water.
#define MAX_STAGE_TERRAIN_RECTS 64

typedef struct {
    int px;        // left edge, map scroll-distance coordinates
    int y;         // top edge in play-area coordinates
} StageTerrainHardpoint;

// What clearing the stage awards the run. Declared per stage so the
// boss salvage and the devtools stage select share one source of truth:
// starting at stage N is defined as holding the awards of stages 1..N-1
// (GrantUpgradesThroughStage in stage.h).
typedef enum {
    UPGRADE_AWARD_NONE,
    UPGRADE_AWARD_MORTAR,
    UPGRADE_AWARD_TARGETING_COMPUTER
} UpgradeAward;

// One stage's compiled content behind a single handle: the engine reads
// the current stage through GameState.stageNumber + GetStageDescriptor
// (stage.h) instead of naming STAGE1_* directly, so adding Stage 2 is a
// new generated table plus one descriptor row - no engine changes.
typedef struct {
    const StageSpawnEvent *events;
    int eventCount;
    const StageTerrainFootprint *terrain;
    int terrainCount;
    const StageTerrainHardpoint *hardpoints;
    int hardpointCount;
    int lengthPx;
    UpgradeAward award;
} StageDescriptor;

extern const StageSpawnEvent STAGE1_EVENTS[];
extern const int STAGE1_EVENT_COUNT;
extern const StageTerrainFootprint STAGE1_TERRAIN[];
extern const int STAGE1_TERRAIN_COUNT;
extern const StageTerrainHardpoint STAGE1_TERRAIN_HARDPOINTS[];
extern const int STAGE1_TERRAIN_HARDPOINT_COUNT;
extern const int STAGE1_LENGTH_PX;

extern const StageSpawnEvent STAGE2_EVENTS[];
extern const int STAGE2_EVENT_COUNT;
extern const StageTerrainFootprint STAGE2_TERRAIN[];
extern const int STAGE2_TERRAIN_COUNT;
extern const StageTerrainHardpoint STAGE2_TERRAIN_HARDPOINTS[];
extern const int STAGE2_TERRAIN_HARDPOINT_COUNT;
extern const int STAGE2_LENGTH_PX;

#endif
